[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = "fat"
debug = true

[dependencies]
ahash = "0.8.12"
fast-float = "0.2.0"
rustc-hash = "2.1.1"
